apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: growi-app
  namespace: growi-shimoda
  labels:
    app: growi-app
spec:
  selector:
    matchLabels:
      app: growi-app
  replicas: 1 # 共有ディスクでpodの2つ目を建てようとするとmountでコケる致命的なエラーがあるため、実質1が上限である
  template:
    metadata:
      labels:
        app: growi-app
      name: growi-app
    spec:
      containers:
      - name: growi-app
        image: weseek/growi:3
        env:
        - name: APP_SITE_URL
          value: "https://wiki.dev.example.com"
        - name: MONGO_URI
          value: "mongodb://sv-growi-mongo:27017/growi"
        - name: ELASTICSEARCH_URI
          value: "http://sv-growi-elasticsearch:9200/growi"
        - name: PASSWORD_SEED
          value: "changeme"
        - name: FILE_UPLOAD
          value: "local"
        - name: FORCE_WIKI_MODE
          value: "private"
        - name: HACKMD_URI
          value: "https://hackmd.dev.example.com"
        - name: HACKMD_URI_FOR_SERVER
          value: "http://sv-growi-hackmd:3010"
        - name: MATHJAX
          value: "1"
        - name: PLANTUML_URI
          value: "http://www.plantuml.com/plantuml"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /_api/v3/healthcheck
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: growi-data
          mountPath: /data
      volumes:
      - name: growi-data
        persistentVolumeClaim:
          claimName: pvc-growi-app
