## hackmd elasticsearch なし版　ドキュメント
# define Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: growi-wiki-parts
---
# Storege
## for growi-app

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-growi-app
  namespace: growi-wiki-parts
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-growi-app
  resources:
    requests:
      storage: 10Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-growi-mongodb
  namespace: growi-wiki-parts
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-growi-mongodb
  resources:
    requests:
      storage: 10Gi
---
# Database(mongo)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: growi-mongo
  namespace: growi-wiki-parts
  labels:
    app: growi-mongo
spec:
  serviceName: "growi-mongo"
  selector:
    matchLabels:
      app: growi-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: growi-mongo
      name: growi-mongo
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: growi-mongo
        image: mongo:3.6
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: growi-mongodb-data
          mountPath: /data/db
      volumes:
      - name: growi-mongodb-data
        persistentVolumeClaim:
          claimName: pvc-growi-mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: sv-growi-mongo
  namespace: growi-wiki-parts
  labels:
    app: growi-mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: growi-mongo
---

# Growi Application
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: growi-app
  namespace: growi-wiki-parts
  labels:
    app: growi-app
spec:
  selector:
    matchLabels:
      app: growi-app
  replicas: 1 # 共有ディスクでpodの2つ目を建てようとするとmountでコケる致命的なエラーがあるため、実質1が上限である
  template:
    metadata:
      labels:
        app: growi-app
      name: growi-app
    spec:
      containers:
      - name: growi-app
        image: weseek/growi:3
        env:
        - name: APP_SITE_URL
          value: "https://wiki.dev.example.com"
        - name: MONGO_URI
          value: "mongodb://sv-growi-mongo:27017/growi"
        - name: PASSWORD_SEED
          value: "changeme"
        - name: FILE_UPLOAD
          value: "local"
        - name: FORCE_WIKI_MODE
          value: "private"
        - name: MATHJAX
          value: "1"
        - name: PLANTUML_URI
          value: "http://www.plantuml.com/plantuml"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /_api/v3/healthcheck
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: growi-data
          mountPath: /data
      volumes:
      - name: growi-data
        persistentVolumeClaim:
          claimName: pvc-growi-app
---
apiVersion: v1
kind: Service
metadata:
  name: sv-growi-app
  namespace: growi-wiki-parts
  labels:
    app: growi-app
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: growi-app
---
# Ingress and Certificate and IP settings
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: cert-growi-app
  namespace: growi-wiki-parts
spec:
  domains:
    - wiki.dev.example.com
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: cert-growi-hackmd
  namespace: growi-wiki-parts
spec:
  domains:
    - hackmd.dev.example.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-growi
  namespace: growi-wiki-parts
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: "ip-growi"
    networking.gke.io/managed-certificates: "cert-growi-app,cert-growi-hackmd"
spec:
  rules:
  - host: wiki.dev.example.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: sv-growi-app
          servicePort: 80
  - host: hackmd.dev.example.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: sv-growi-hackmd
          servicePort: 3010
