# Storege
## for growi-app
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-growi-app
  namespace: shimoda-growi
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-growi-app
  gcePersistentDisk:
    pdName: disk-growi-app
    fsType: ext4
