apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grow-app
  namespace: shimoda-growi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-growi-app
  resources:
    requests:
      storage: 10Gi
