apiVersion: v1
kind: Service
metadata:
  name: sv-growi-mongo
  namespace: growi-shimoda
  labels:
    app: growi-mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: growi-mongo
