apiVersion: v1
kind: Service
metadata:
  name: sv-growi-app
  labels:
    app: growi-app
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: growi-app