apiVersion: v1
kind: Service
metadata:
  labels:
    app: growi-elasticsearch
  name: sv-growi-elasticsearch
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: growi-elasticsearch